### ISSUE TITLE
Right arrow usage in the Input submits in Command line tutorial

### ISSUE THREAD

**Issue by RamParthiban** [jsjoeio/mentored.dev#121]
Hi @jsjoeio, First of all, Great Job on the mentored.dev. It is awesome.

I tried to enter the command in the command line. I did a minor typo in the command so I used arrow keys to go back to the typo point. The Left arrow worked fine. But When I hit the right arrow to bring back the cursor to the continuation spot it got Submitted.

**Comment by jsjoeio** [comment]
Hi @RamParthiban - thank you!

And thanks for opening this issue. Unfortunately that is by design. Some people will use the 'Enter' key to submit their answer and others can click the right arrow to do that. 

I did it this way because I thought it made the most sense. I hope that makes sense and I'm sorry for the confusion!
